version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3200:3200"

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend
