# Generated by Django 4.2.6 on 2023-10-09 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productOwnerName', models.CharField(max_length=200)),
                ('scrumMasterName', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('methodology', models.CharField(choices=[('AG', 'Agile'), ('WA', 'Waterfall')], default='AG', max_length=2)),
                ('location', models.CharField(blank=True, default=None, max_length=2048)),
                ('Developers', models.ManyToManyField(to='core.developers')),
            ],
        ),
    ]
