# Generated by Django 4.2.6 on 2023-10-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_developers_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Developers',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
