# Generated by Django 4.2.6 on 2023-10-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_developers_delete_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Developers',
            field=models.JSONField(default=[]),
        ),
    ]
