# Generated by Django 4.2.6 on 2023-10-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='methodology',
            field=models.CharField(choices=[('Agile', 'Agile'), ('Waterfall', 'Waterfall')], default='Agile', max_length=10),
        ),
    ]
