# Generated by Django 4.2.6 on 2023-10-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_methodology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Developers',
            field=models.JSONField(default=list),
        ),
    ]
